### ISSUE TITLE
Epic: Production style Riff.CC

### ISSUE THREAD

**Issue by Zorlin** [riffcc/orbiter#6]
We commissioned a graphic designer on Fiverr, `rubel_01`, to create a series of designs for what Riff.CC should look like.

This epic tracks the work involved in converting Riff.CC Ceramic to suit that design.

Design: 
[Home](https://user-images.githubusercontent.com/1369772/211533687-5fba728b-964e-40d5-881d-fc5178b37a8a.png)
[Music](https://user-images.githubusercontent.com/1369772/211534052-27ecf992-e379-4a5c-aba4-103886d2c7a0.png)
[Album details](https://user-images.githubusercontent.com/1369772/211534014-5dbf7f86-43a7-42e5-84c9-5be582f2edb6.png)

- [x] riffcc/ceramic-riff-web#6 
- [ ] riffcc/ceramic-riff-web#12
- [x] riffcc/ceramic-riff-web#11 
- [x] riffcc/ceramic-riff-web#19 
- [ ] riffcc/ceramic-riff-web#10
- [ ] More to come...
